### ISSUE TITLE
Running with hands17 net

### ISSUE THREAD

**Issue by joohaeng** [xinghaochen/Pose-REN#4]
Thank you for sharing the pre-trained net with the hands17 dataset.

I tried to run the real-time demo with the new network after renaming them, but failed.

I guess the the current code repository seems to be updated to support hands17.

I checked several places in the source codes, but lost to track.

---

Traceback (most recent call last):
  File "realsense_realtime_demo_librealsense2.py", line 93, in <module>
    main()
  File "realsense_realtime_demo_librealsense2.py", line 85, in main
    results = hand_model.detect_image(depth)
  File "/home/joohaeng/Downloads/Pose-REN-master/src/utils/model_pose_ren.py", line 74, in detect_image
    return self.detect_images([img])[0, ...]
  File "/home/joohaeng/Downloads/Pose-REN-master/src/utils/model_pose_ren.py", line 58, in detect_images
    init_poses = self._net_init.forward()['fc3']
KeyError: 'fc3'

**Comment by xinghaochen** [comment]
Hi, the output blob for prototxt of hands17 model is a bit different from others.
Specifically, the output blob should be changed to 'predict' for hands17. I have just update the repo to fix this problem.
Hope it helps.
